# Generated by Django 5.1.3 on 2024-11-22 12:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='finalboth_jagah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('registered_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('key_id', models.CharField(max_length=100)),
                ('licence_key', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'finalboth_licencekey',
            },
        ),
        migrations.CreateModel(
            name='LicenceKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('key_id', models.CharField(max_length=100)),
                ('licence_key', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('registered_on', models.DateTimeField(default=django.utils.timezone.localtime)),
            ],
            options={
                'db_table': 'LicenceKey',
            },
        ),
    ]
