# Generated by Django 5.1.3 on 2024-11-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licencekey',
            name='key_status',
            field=models.CharField(choices=[('active', 'Active')], default='Active', max_length=10),
        ),
        migrations.AddField(
            model_name='licencekey',
            name='valid_upto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
