# Generated by Django 5.1.3 on 2024-11-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_licencekey_key_status_licencekey_valid_upto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencekey',
            name='registered_on',
            field=models.DateTimeField(blank=True, max_length=20, null=True),
        ),
    ]
