# Generated by Django 5.1.3 on 2024-11-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_licencekey_registered_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencekey',
            name='key_status',
            field=models.CharField(default='Active', max_length=10),
        ),
    ]
