# Generated by Django 5.1.3 on 2024-11-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_licencekey_key_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licencekey',
            name='first_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='licencekey',
            name='key_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='licencekey',
            name='key_status',
            field=models.CharField(default='Active', max_length=500),
        ),
        migrations.AlterField(
            model_name='licencekey',
            name='last_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='licencekey',
            name='licence_key',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='licencekey',
            name='mac_address',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='licencekey',
            name='phone',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='licencekey',
            name='registered_on',
            field=models.DateTimeField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='licencekey',
            name='valid_upto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
